FROM node:18-bullseye-slim

WORKDIR /app

COPY src/dashboard/package*.json ./
RUN npm install
COPY src/dashboard/ ./
RUN npm run build

RUN groupadd --gid 1001 nodejs && \
    useradd --uid 1001 --gid 1001 --create-home --shell /bin/bash nodejs
USER nodejs

EXPOSE 3000

CMD ["npm", "start"]
