FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY node_modules/ ./node_modules/
COPY src/ ./src/
COPY config/ ./config/
COPY ["old-way-we-doing-for-algotrading/Symphony_30-09-2025/Test/NIFTY 50.csv", "./data/history/NIFTY_50.csv"]

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 -G nodejs && \
    mkdir -p /app/logs && \
    chown nodejs:nodejs /app/logs
USER nodejs

# Expose default port
EXPOSE 3000

CMD ["node", "src/index.js"]
